# Prometheus configuration for Digital English Academy

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node exporter for system metrics
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Application metrics
  - job_name: "dea-app"
    static_configs:
      - targets: ["app:80"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Redis metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # MongoDB metrics
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]

  # Nginx metrics
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  # Docker metrics
  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Blackbox monitoring for external endpoints
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://digitalenglishacademy.com
          - https://digitalenglishacademy.com/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
